### ISSUE TITLE
Feature: Player Controller

### ISSUE THREAD

**Issue by yanniboi** [LPGameDevs/EditarrrPublic#10]
### Description

We need to be able to play the game. The result should be a `Player` prefab that we can spawn into a level.

In order to build this I would suggest creating a new scene, adding a tilemap to be able to draw a floor and then add a square sprite to start working on. Animations/etc can be added at any point and all the required sprites should already be included in the project.

### Todo

Everything...

MVP

- [x] input mapping 
- [x] player movement 
- [x] collisions 
- [x] animation

Lower priority

- [x] health 
- [x] death 
- [ ] respawn 

### Notes

We may want to use Tarodev player controller as a starting point:

https://github.com/Matthew-J-Spencer/Ultimate-2D-Controller

**Comment by yanniboi** [comment]
I've added the input mapping to the player controller so now we can tell with movement or jumping is happening.

https://user-images.githubusercontent.com/1744957/229808714-9a9feb7c-44ea-49ac-90a7-51f933c1b400.mp4

**Comment by yanniboi** [comment]
*Research credit*: `@Kiqa`

> GMTKs platformer toolkit is pretty good for understanding player controllers in a 2D sense as well. 

- https://gmtk.itch.io/platformer-toolkit
- https://github.com/Shinjingi/Unity2D-Platform-Character-Controller

**Comment by yanniboi** [comment]
I've split this up into several smaller tasks so people can assign those without having the whole PlayerController assigned:

- https://github.com/orgs/LPGameDevs/projects/4/views/1?pane=issue&itemId=24980419

**Comment by X-0X** [comment]
I would like to take the lead on the player animations. I basically understand how it's done but definitely need practice! I'm also happy to assist whoever wants to work on Health and Movement portions, and if anyone else is interested to work on the animation portion, let's talk!

**Comment by CalmPewter** [comment]
This issue is marked as In Progress but has no assignees. Is it actively being worked on or should I have a look?
