### ISSUE TITLE
Delete Scores for Levels that were published when they were drafts

### ISSUE THREAD

**Issue by HaywardMorihara** [LPGameDevs/EditarrrPublic#204]
We can determine this by comparing the timestamp of when the score was published, and if it's less than the "Last Updated" date of the level, then it can be deleted.

Gonna do it with a script because it'd be a lot of work to manually track down all these scores

**Comment by HaywardMorihara** [comment]
> We can determine this by comparing the timestamp of when the score was published, and if it's less than the "Last Updated" date of the level, then it can be deleted.

@yanniboi this should be accurate, right? Because we do a PUT on the level to make it PUBLISHED rather than DRAFT. And when we do a PUT, we update the LAST_UPDATED timestamp. Or were you thinking about a different approach?

The only thing is: a level _could_ be updated for a reason other than being published? Except, I figure we should make all prior scores moot at that point anyway? Unless is was simply metadata like the "Level Name"

**Comment by yanniboi** [comment]
This is my approach.

Load all levels and load all the scores.

Loop over all the scores and check the level data. If the level is not published, delete the score. If the level is published but the score date is smaller than the level updated date, delete the score.

Getting published is the last change that happens to a level. After that the updated time shouldn't change. So any score that was created prior to publishing should not exist.

**Comment by yanniboi** [comment]
Any updates that could be made after publishing would be done by admin through the UI and wouldn't change the updatedDate

**Comment by HaywardMorihara** [comment]
Sounds good, I will make a script that:

```sh
# Fetch every level

# For each level, get all scores

 # For each score:
    # If the level is DRAFT, delete the score
    # If `score.scoreSubmittedAt` < `leveel.levelUpdatedAt`, delete the score
```

**Comment by HaywardMorihara** [comment]
# Plan

- [ ] Dry run in `develop` and verify and save the output
- [ ] Run in `develop` and verify
  - [ ] Verify that not all scores are deleted
  - [ ] Verify at least one of the levels with expected scores to be deleted and scores that should not have been deleted and make sure that the appropriate scores were deleted
- [ ] Dry run in `production` and verify and save the output
- [ ] Run in `production`
  - [ ] Verify that not all scores are deleted
  - [ ] Verify at least one of the levels with expected scores to be deleted and scores that should not have been deleted and make sure that the appropriate scores were deleted
