### ISSUE TITLE
Player takes damage when they touch spikes.

### ISSUE THREAD

**Issue by yanniboi** [LPGameDevs/EditarrrPublic#32]
We should add a general script that gives the player damage when they touch an object that has that script. 

This script can be added to the tilemap that has the spikes on it and later also to the enemies.

**Comment by Bolrik** [comment]
This component should also have an optional field for knockback, which would be applied on touch. That would add an extra strategy to play with as long as we have 1+ Health instead of one hit.
Like damage boosting, etc.

**Comment by yanniboi** [comment]
I've created #38 for that feature
