### ISSUE TITLE
Player Wins at treasure chest

### ISSUE THREAD

**Issue by yanniboi** [LPGameDevs/EditarrrPublic#33]
Part of [#11](https://github.com/LPGameDevs/EditarrrPublic/issues/11)

We need a prefab to spawn for the treasure chest.

The treasure chest needs a collider and we need a new layer for "interactable" objects.

When the player enters the collider we should fire a win event (see https://github.com/LPGameDevs/EditarrrPublic/discussions/17)

### Future additions

We will want to have a popup that shows when the player wins. We will also want to "stop gameplay" a similar mechanic to when the pause menu is activated stopping game time and player input etc.

**Comment by CalmPewter** [comment]
This seems to have been completed based on your post on the discord, right Yan?
