### ISSUE TITLE
PlayerController: Invincibility Frames

### ISSUE THREAD

**Issue by yanniboi** [LPGameDevs/EditarrrPublic#39]
Maybe you could add some optional invincibility frames to the Health Script. 

_Originally posted by @Bolrik in https://github.com/LPGameDevs/EditarrrPublic/issues/28#issuecomment-1501732147_

**Comment by yanniboi** [comment]
I think the way to do this is to have a bool for _canTakeDamage and set this to false for 0.5 seconds (or whatever feels good) after damage is taken.

**Comment by Bolrik** [comment]
I agree with that. Also, the ApplyDamage method should return true or false depending on if damage was taken or not.

**Comment by yanniboi** [comment]
>  @yanniboi moves quick!

I have github notifications in Discord :wink: 

![image](https://user-images.githubusercontent.com/1744957/231125019-c10bbaf1-0c44-438e-b08f-c90398e78324.png)
