### ISSUE TITLE
Feature: Level Feedback

### ISSUE THREAD

**Issue by BastisBastis** [LPGameDevs/EditarrrPublic#42]
Do we want a simple system that allows players to give feedback and/or ratings to levels?

Feedback would fit the idea of the community, which is to help developers increase their game dev skills.

Ratings could help with the competition aspect of the jam.

Both feedback and ratings could be private and only visible to the level creator.

It would require some back end work and figuring out a good solution for sharing the feedback with the creator. Using e-mail for instance might lead to GDPR and Privacy issues for instance.

**Comment by yanniboi** [comment]
Yup this is 100% something we want. 

I think feedback and ratings should be private during the competition (but we should get a count for how many ratings a level has had or show all the levels you as a player have rated). This gives us (reviewers) a chance to check through all the reviews ( just to make sure nothing too awful gets posted 😉 ). Then at the end we can publish all responses to everyone. 

I'd like to avoid anyone needing to register emails etc. for gdpr/privacy. But if we really needed to I would consider doing discord login or something like that 😉
