### ISSUE TITLE
Define the Backend APIs and DB Structure

### ISSUE THREAD

**Issue by HaywardMorihara** [LPGameDevs/EditarrrPublic#53]
We're building a backend service/DB to store the data about levels.

The proposed APIs we'll need for this backend service are listed in https://github.com/LPGameDevs/EditarrrPublic/blob/develop/backend/README.md#apis

We need to:
* Define the API structure for the APIs
* Determine how the level data (including high scores) get stored and access from the DynamoDB
* Determine how the level preview images will get stored in S3
* Document the solution

Once we've come up with the plan, we can implement the APIs, divided into 3 Issues:
* https://github.com/LPGameDevs/EditarrrPublic/issues/54
* https://github.com/LPGameDevs/EditarrrPublic/issues/55
* https://github.com/LPGameDevs/EditarrrPublic/issues/56

See https://github.com/LPGameDevs/EditarrrPublic/blob/develop/backend/README.md for the proposed backend setup.

**Comment by yanniboi** [comment]
@HaywardMorihara yea sorry, its because the PR auto closed the ticket when I merged it. Not sure what caused that connection...

**Comment by HaywardMorihara** [comment]
> @HaywardMorihara yea sorry, its because the PR auto closed the ticket when I merged it. Not sure what caused that connection...

No worries! I  made that connection 😁 haha
