### ISSUE TITLE
Start time on input

### ISSUE THREAD

**Issue by Bolrik** [LPGameDevs/EditarrrPublic#81]
Somewhat related to #67
It's a little QoL feature, but i think the game would benefit from only starting level time as soon as the first input hit.
Previously, it was very difficult to constantly hit a frame perfect start 😎

**Comment by CalmPewter** [comment]
Good idea, and should be simple to implement.
Unless @yanniboi has a problem with this, I'll work it into my current commit.

**Comment by yanniboi** [comment]
There is still a little tweak we could do here. There is a small (maybe half a second) delay at the start where the player hangs in the air.

**Comment by CalmPewter** [comment]
That had to do with the _started bool check in the PlayerController. If false it invoked the Activate method with a 0.5 second delay.
I've removed that part and everything still seems to be working fine, now without startup-delays.
